modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"

[[mods]]
modId="electrona"
version="1.16.5-r2.1.1"
displayName="Electrona"
credits="Credits are on mod's page."
displayURL="http://max-electrona.000webhostapp.com/"
authors="Max094_Reikeb"
description='''
Electrona is a tech mod made by Max094_Reikeb.

It was originally made on MCreator, but then, the r2.0 version ported it off.
'''

[[dependencies.electrona]] #optional
    modId="forge"
    mandatory=true
    versionRange="[37.0.15,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.electrona]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
