modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="electrona"
version="1.16.5-a2.0"
displayName="Electrona"
credits="Credits are on mod's page."
displayURL="https://trello.com/b/iDpxVYxZ/electrona"
authors="Max094_Reikeb"
description='''
Electrona is a tech mod
'''

[[dependencies.electrona]] #optional
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.electrona]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
