# Creates releases on GH Packages when a new version is released
name: Github Packages Release

on:
  release:
    types: [published]

jobs:
  vars:
    name: Get Variables
    runs-on: ubuntu-latest
    outputs:
      mod_id: ${{ steps.mod_id.outputs.value }}
      package_version: ${{ steps.package_version.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Mod ID
        id: mod_id
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'mod_id'

      - name: Package Version
        id: package_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './gradle.properties'
          property: 'package_version'

  jar:
    name: Publish JAR
    runs-on: ubuntu-latest
    needs: [vars]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: "16.0.2"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish JAR with Gradle
        run: ./gradlew publish --max-workers 1
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Artifact
        uses: actions/upload-artifact@v2
        with:
          name: libs
          path: |
            build-out/${{ needs.vars.outputs.mod_id }}-${{ needs.vars.outputs.package_version }}.jar
            build-out/${{ needs.vars.outputs.mod_id }}-${{ needs.vars.outputs.package_version }}-api.jar